### ISSUE TITLE
README of package generated without account for npm deployment instructs reader to install the package from npm

### ISSUE THREAD

**Issue by TNThomas** [ashblue/oyster-package-generator#68]
Ideally, instructions could be generated to add the package from Git instead. That might be hard to set up within the confines of the template schema, though. Provisionally, the misleading download instructions could perhaps just not be generated?

**Comment by ashblue** [comment]
Sorry for the delayed response here. What do you mean by "instructions could be generated to add the package from Git instead"? Also what specific instructions are you referring to?

**Comment by TNThomas** [comment]
Unity package manager supports package installation from a Git URL: https://docs.unity3d.com/Manual/upm-ui-giturl.html
If the user has opted not to use NPM, this would be a sensible fallback.

**Comment by ashblue** [comment]
Oh yeah you can use a Git URL on the nightly branch once you setup cloud deploys. Nightly branch is auto deployed whenever `develop` updates. This is a tradeoff to make up for storing the full Unity3D project architecture in version control.  I think that solves what you're looking for right?

**Comment by TNThomas** [comment]
Kind of? The issue is that the README tells the reader to download from NPM even if the Oyster package wasn't set up to publish to NPM

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ashblue** [comment]
Yeah you'd have to manually edit the README.md if you didn't do an NPM cloud deploy. There would have to be some sort of wizard that would ask questions and generate the docs accordingly. This would be quite a bit of work so it's really an extended feature. Gonna close this one since it's a bit out of scope atm. But please feel free to open a discussion to dig into this more https://github.com/ashblue/oyster-package-generator/discussions

Proejct is really designed to work with cloud deploys. But there is definitely a feature piece in here just for generating a non-cloud deploy package.
